name: Deploy Function App (.NET Core) to DevOpsFunctions20200728121909
on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - master
env:
  AZURE_FUNCTIONAPP_NAME: DevOpsFunctions20200728121909
  AZURE_FUNCTIONAPP_PACKAGE_PATH: .
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.DEVOPSFUNCTIONS20200728121909_PUBLISH_PROFILE }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 3.1.x
  PUBLISH_PROVIDERTYPE: azureFunctionAppLinux
  PUBLISH_RESOURCEID: /subscriptions/07268dd7-4c50-434b-b1ff-67b8164edb41/resourceGroups/vramakFuncrg/providers/Microsoft.Web/sites/DevOpsFunctions20200728121909
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@master
    - name: Setup .NET Core SDK ${{ env.DOTNET_CORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Resolve Project Dependencies Using Dotnet
      run: >
        pushd "./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

        dotnet build --configuration ${{ env.CONFIGURATION }} --output "./output"

        popd
      shell: bash
    - name: Run Azure Functions Action
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output
